[
   
    {
        "facility_id": "FA0206627",
        "record_ID": "PR0303632",
        "PROGRAM_IDENTIFIER": "ROJAS MEXICAN FOOD 2G87024",
        "FACILITY_NAME": "ROJAS MEXICAN FOOD 2G87024",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0210929",
        "record_ID": "PR0303650",
        "PROGRAM_IDENTIFIER": "DANERY'S ANTOJITOS 3W62365",
        "FACILITY_NAME": "DANERY'S ANTOJITOS 3W62365",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0210447",
        "record_ID": "PR0304223",
        "PROGRAM_IDENTIFIER": "TACOS SAN JOSE 3T85656",
        "FACILITY_NAME": "TACOS SAN JOSE 3T85656",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0210441",
        "record_ID": "PR0304478",
        "PROGRAM_IDENTIFIER": "ANTOJITOS EL PRIMO 2U79688",
        "FACILITY_NAME": "ANTOJITOS EL PRIMO 2U79688",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0210443",
        "record_ID": "PR0304536",
        "PROGRAM_IDENTIFIER": "NENA'S TACOS 3Z55557",
        "FACILITY_NAME": "NENA'S TACOS 3Z55557",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0250851",
        "record_ID": "PR0305602",
        "PROGRAM_IDENTIFIER": "HERMANOS LOPEZ 5Z11956",
        "FACILITY_NAME": "HERMANOS LOPEZ 5Z11956",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0209871",
        "record_ID": "PR0305960",
        "PROGRAM_IDENTIFIER": "SAP CENTER-102 ABC PORTABLE",
        "FACILITY_NAME": "SAP CENTER SAN JOSE",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4089995860",
        "city": "SAN JOSE",
        "ZIP": "95113"
    },
    {
        "facility_id": "FA0230702",
        "record_ID": "PR0306123",
        "PROGRAM_IDENTIFIER": "TACOS AL PASTOR 8S33970",
        "FACILITY_NAME": "TACOS AL PASTOR 8S33970",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084367122",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0206777",
        "record_ID": "PR0307940",
        "PROGRAM_IDENTIFIER": "LA CHAPARRA 6A05118",
        "FACILITY_NAME": "LA CHAPARRA 6A05118",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084367522",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0240521",
        "record_ID": "PR0350060",
        "PROGRAM_IDENTIFIER": "TACOS LOS 3 HERMANOS 4TH2809",
        "FACILITY_NAME": "TACOS LOS 3 HERMANOS 4TH2809",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "NULL",
        "city": "SAN JOSE",
        "ZIP": "95110"
    },
    {
        "facility_id": "FA0250170",
        "record_ID": "PR0360451",
        "PROGRAM_IDENTIFIER": "DULCE VICTORIA AMERICAN AND MEXICAN FOOD 8V21201",
        "FACILITY_NAME": "DULCE VICTORIA AMERICAN AND MEXICAN FOOD",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0250247",
        "record_ID": "PR0360559",
        "PROGRAM_IDENTIFIER": "MC FOOD INC. 5M62715",
        "FACILITY_NAME": "MC FOOD INC. 5M62715",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082757191",
        "city": "SAN JOSE",
        "ZIP": "95127"
    },
    {
        "facility_id": "FA0250748",
        "record_ID": "PR0363856",
        "PROGRAM_IDENTIFIER": "CALIFORNIA DRIVEN 8K70456",
        "FACILITY_NAME": "CALIFORNIA DRIVEN 8K70456",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082805014",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0251878",
        "record_ID": "PR0366151",
        "PROGRAM_IDENTIFIER": "SABOR MEXICO 2U78848",
        "FACILITY_NAME": "SABOR MEXICO 2U78848",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4087998011",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0256183",
        "record_ID": "PR0374097",
        "PROGRAM_IDENTIFIER": "SABOR CASERO INTERNACIONAL 7A28200",
        "FACILITY_NAME": "SABOR CASERO INTERNACIONAL 7A28200",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "6502750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0257608",
        "record_ID": "PR0376914",
        "PROGRAM_IDENTIFIER": "2/1/24FELIPE EL KORA 4EU9369",
        "FACILITY_NAME": "FELIPE EL KORA 4EU9369",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4089262810",
        "city": "SAN JOSE",
        "ZIP": "95116"
    },
    {
        "facility_id": "FA0258947",
        "record_ID": "PR0379318",
        "PROGRAM_IDENTIFIER": "LAS GRULLAS MEXICAN GRILL 7G22197",
        "FACILITY_NAME": "LAS GRULLAS MEXICAN GRILL 7G22197",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4089349695",
        "city": "ALVISO",
        "ZIP": "95002"
    },
    {
        "facility_id": "FA0259010",
        "record_ID": "PR0379396",
        "PROGRAM_IDENTIFIER": "TACOS LA ESTRELLA 50083P2",
        "FACILITY_NAME": "TACOS LA ESTRELLA 50083P2",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082943873",
        "city": "SAN JOSE",
        "ZIP": "95116"
    },
     {
        "facility_id": "FA0260183",
        "record_ID": "PR0381307",
        "PROGRAM_IDENTIFIER": "EL TACO DE ORO 8A62811",
        "FACILITY_NAME": "EL TACO DE ORO 8A62811",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4089400674",
        "city": "ALVISO",
        "ZIP": "95002"
    },
    {
        "facility_id": "FA0260274",
        "record_ID": "PR0381477",
        "PROGRAM_IDENTIFIER": "PAULINA'S CATERING 8D94835",
        "FACILITY_NAME": "PAULINA'S CATERING 8D94835",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0260275",
        "record_ID": "PR0381478",
        "PROGRAM_IDENTIFIER": "ROSARIOS TACOS 4SG1630",
        "FACILITY_NAME": "ROSARIOS TACOS 4SG1630",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084645480",
        "city": "SAN JOSE",
        "ZIP": "95110"
    },
    {
        "facility_id": "FA0260459",
        "record_ID": "PR0381733",
        "PROGRAM_IDENTIFIER": "LA JACARANDA OAXAQUENA 4HT6843",
        "FACILITY_NAME": "LA JACARANDA OAXAQUENA 4HT6843",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0261182",
        "record_ID": "PR0382958",
        "PROGRAM_IDENTIFIER": "EL PAISA ARAUJOS TAQUERIA #2 4FF1682",
        "FACILITY_NAME": "EL PAISA ARAUJOS TAQUERIA #2 4FF1682",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4083000814",
        "city": "SAN JOSE",
        "ZIP": "95111"
    },
   
    {
        "facility_id": "FA0262597",
        "record_ID": "PR0385817",
        "PROGRAM_IDENTIFIER": "GUTIERREZ AUTENTICA COMIDA MEXICANA 35373R1",
        "FACILITY_NAME": "GUTIERREZ AUTENTICA COMIDA MEXICANA 35373R1",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0263306",
        "record_ID": "PR0387826",
        "PROGRAM_IDENTIFIER": "ANTOJITOS MI MORENITA 4N99604",
        "FACILITY_NAME": "ANTOJITOS MI MORENITA 4N99604",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
   
    {
        "facility_id": "FA0264929",
        "record_ID": "PR0390808",
        "PROGRAM_IDENTIFIER": "CON SABOR A MEXICO #2 3Z56157",
        "FACILITY_NAME": "CON SABOR A MEXICO #2 3Z56157",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4083935599",
        "city": "SAN JOSE",
        "ZIP": "95133"
    },
    {
        "facility_id": "FA0265000",
        "record_ID": "PR0390924",
        "PROGRAM_IDENTIFIER": "CMFO-ANTOJITOS PANZAS VERDES 4KJ4798",
        "FACILITY_NAME": "ANTOJITOS PANSAS VERDES 4KJ4798",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084601697",
        "city": "SUNNYVALE",
        "ZIP": "94086"
    },
    {
        "facility_id": "FA0265422",
        "record_ID": "PR0391652",
        "PROGRAM_IDENTIFIER": "CMFO - ANTOJITOS PANZAS VERDES 4TE9973",
        "FACILITY_NAME": "ANTOJITOS PANZAS VERDES 4TE9973",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084398903",
        "city": "SAN JOSE",
        "ZIP": "95136"
    },
    {
        "facility_id": "FA0265732",
        "record_ID": "PR0392393",
        "PROGRAM_IDENTIFIER": "TACOS EL LIDER 4KL6498",
        "FACILITY_NAME": "TACOS EL LIDER 4KL6498",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088187854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0265847",
        "record_ID": "PR0392636",
        "PROGRAM_IDENTIFIER": "TACOS SANTIAGUITO 57424M1",
        "FACILITY_NAME": "TACOS SANTIAGUITO 57424M1",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0265950",
        "record_ID": "PR0392756",
        "PROGRAM_IDENTIFIER": "CMFO-ANTOJITOS PANZAS VERDES 4KU4363",
        "FACILITY_NAME": "ANTOJITOS PANZAS VERDES 4KU4363",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084601697",
        "city": "SUNNYVALE",
        "ZIP": "94086"
    },
    {
        "facility_id": "FA0266175",
        "record_ID": "PR0393026",
        "PROGRAM_IDENTIFIER": "ROYAL DOSA 4LH3924",
        "FACILITY_NAME": "ROYAL DOSA 4LH3924",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4087281358",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0266567",
        "record_ID": "PR0393604",
        "PROGRAM_IDENTIFIER": "CMFO-LA ETERNA PRIMAVERA 4LC9708",
        "FACILITY_NAME": "LA ETERNA PRIMAVERA 4LC9708",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95125"
    },
    {
        "facility_id": "FA0267702",
        "record_ID": "PR0395001",
        "PROGRAM_IDENTIFIER": "MEX*CAL ON WHEELS 8Y55239",
        "FACILITY_NAME": "MEX*CAL ON WHEELS 8Y55239",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084209308",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0268101",
        "record_ID": "PR0395661",
        "PROGRAM_IDENTIFIER": "ANTOJITOS EL ZOCALO INC. 4LH3930",
        "FACILITY_NAME": "ANTOJITOS EL ZOCALO INC 4LH3930",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4086202648",
        "city": "SAN JOSE",
        "ZIP": "95122"
    },
    {
        "facility_id": "FA0268417",
        "record_ID": "PR0397885",
        "PROGRAM_IDENTIFIER": "CMFO - TACOS EL TUCANAZO 4LJ8314",
        "FACILITY_NAME": "TACOS EL TUCANAZO 4LJ8314",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4085097721",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0268547",
        "record_ID": "PR0398312",
        "PROGRAM_IDENTIFIER": "EL BURRITO CRAZY 4MK9894",
        "FACILITY_NAME": "EL BURRITO CRAZY 4MK9894",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082174860",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0268644",
        "record_ID": "PR0399032",
        "PROGRAM_IDENTIFIER": "TAQUERIA REYES 4LJ7813",
        "FACILITY_NAME": "TAQUERIA REYES 4LJ7813",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084367522",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0268706",
        "record_ID": "PR0399177",
        "PROGRAM_IDENTIFIER": "JUDIE'S TACOS LOCOS 20529G2",
        "FACILITY_NAME": "JUDIE'S TACOS LOCOS 20529G2",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084367522",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0269538",
        "record_ID": "PR0401059",
        "PROGRAM_IDENTIFIER": "CMFO - TACOS DEL GUERO DE GILROY 4LK8922",
        "FACILITY_NAME": "TACOS DEL GUERO DE GILROY 4LK8922",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4086202301",
        "city": "GILROY",
        "ZIP": "95020"
    },
    {
        "facility_id": "FA0269966",
        "record_ID": "PR0401810",
        "PROGRAM_IDENTIFIER": "EL BUEN PASTOR 6Z36241",
        "FACILITY_NAME": "VEL BUEN PASTOR 6Z36241",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },

    {
        "facility_id": "FA0269973",
        "record_ID": "PR0401817",
        "PROGRAM_IDENTIFIER": "LOS JAROCHOS GRILL 12770G1",
        "FACILITY_NAME": "LOS JAROCHOS GRILL 12770G1",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0271308",
        "record_ID": "PR0409647",
        "PROGRAM_IDENTIFIER": "TAKOZ MOD MEX 2U79558",
        "FACILITY_NAME": "TAKOZ MOD MEX 2U79558",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0304660",
        "record_ID": "PR0409658",
        "PROGRAM_IDENTIFIER": "LAS GRULLAS MEXICAN GRILL #2 41862V3",
        "FACILITY_NAME": "LAS GRULLAS MEXICAN GRILL #2 41862V3",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4089349695",
        "city": "ALVISO",
        "ZIP": "95002"
    },
    
    {
        "facility_id": "FA0271607",
        "record_ID": "PR0410385",
        "PROGRAM_IDENTIFIER": "CMFO-TACOS EL VIEJON 4LW8188",
        "FACILITY_NAME": "TACOS EL VIEJON 4LW8188",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4087574894",
        "city": "SAN JOSE",
        "ZIP": "95110"
    },
    {
        "facility_id": "FA0271751",
        "record_ID": "PR0410794",
        "PROGRAM_IDENTIFIER": "LAS GEMELAS SAGRERO 4MB8361",
        "FACILITY_NAME": "LAS GEMELAS SAGRERO 4MB8361",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0271786",
        "record_ID": "PR0410886",
        "PROGRAM_IDENTIFIER": "TACOS SAN JOSE #1 4EX7842",
        "FACILITY_NAME": "TACOS SAN JOSE #1 4EX7842",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0271916",
        "record_ID": "PR0411182",
        "PROGRAM_IDENTIFIER": "TACOS AL VAPOR BLANQUITA 4GX5517",
        "FACILITY_NAME": "TACOS AL VAPOR BLANQUITA 4GX5517",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167054",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0272027",
        "record_ID": "PR0411342",
        "PROGRAM_IDENTIFIER": "MIO TACO 41445C2",
        "FACILITY_NAME": "MIO TACO 41445C2",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4089666081",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0272140",
        "record_ID": "PR0411583",
        "PROGRAM_IDENTIFIER": "TACOMANIA 4MA3958",
        "FACILITY_NAME": "TACOMANIA 4MA3958",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4086085317",
        "city": "SAN JOSE",
        "ZIP": "95111"
    },
  
    
    {
        "facility_id": "FA0272772",
        "record_ID": "PR0412534",
        "PROGRAM_IDENTIFIER": "CMFO-TACOS LA OAXAQUENA 4KW9139",
        "FACILITY_NAME": "TACOS LA OAXAQUENA 4KW9139",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0272975",
        "record_ID": "PR0412793",
        "PROGRAM_IDENTIFIER": "BIRRIERIA EL PRIMO 6F85921",
        "FACILITY_NAME": "BIRRIERIA EL PRIMO 6F85921",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "6692052912",
        "city": "SAN JOSE",
        "ZIP": "95111"
    },
    {
        "facility_id": "FA0273050",
        "record_ID": "PR0412898",
        "PROGRAM_IDENTIFIER": "CMFO-SANCHEZ TACOS 4KH8536",
        "FACILITY_NAME": "SANCHEZ TACOS 4KH8536",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4086144046",
        "city": "GILROY",
        "ZIP": "95037"
    },

    {
        "facility_id": "FA0273174",
        "record_ID": "PR0413043",
        "PROGRAM_IDENTIFIER": "TACOS DEL GUERO 4KU4738",
        "FACILITY_NAME": "TACOS DEL GUERO 4KU4738",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4086202301",
        "city": "GILROY",
        "ZIP": "95020"
    },

    {
        "facility_id": "FA0273370",
        "record_ID": "PR0413306",
        "PROGRAM_IDENTIFIER": "TACOS TIME 4LF1353",
        "FACILITY_NAME": "TACOS TIME 4LF1353",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0273485",
        "record_ID": "PR0413459",
        "PROGRAM_IDENTIFIER": "TACOS LA ESMERALDA 4MJ5355",
        "FACILITY_NAME": "TACOS LA ESMERALDA 4MJ5355",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0273995",
        "record_ID": "PR0414405",
        "PROGRAM_IDENTIFIER": "TAQUERIA PATZCUARO 4MD5102",
        "FACILITY_NAME": "TAQUERIA PATZCUARO 4MD5102",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0274427",
        "record_ID": "PR0414994",
        "PROGRAM_IDENTIFIER": "EL VIEJON MEXICAN FOOD 17624X3",
        "FACILITY_NAME": "EL VIEJON MEXICAN FOOD 17624X3",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0274572",
        "record_ID": "PR0415172",
        "PROGRAM_IDENTIFIER": "SUPER TACOS PINO SUAREZ 9AUB046",
        "FACILITY_NAME": "SUPER TACOS PINO SUAREZ 9AUB046",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },    
    {
        "facility_id": "FA0274726",
        "record_ID": "PR0415310",
        "PROGRAM_IDENTIFIER": "TACOS SOLECITA 40896P3",
        "FACILITY_NAME": "TACOS SOLECITA 40896P3",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0274884",
        "record_ID": "PR0415491",
        "PROGRAM_IDENTIFIER": "MENDEZ TAQUERIA 15765M1",
        "FACILITY_NAME": "MENDEZ TAQUERIA 15765M1",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084367522",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0276126",
        "record_ID": "PR0417276",
        "PROGRAM_IDENTIFIER": "EL TACOLOCO 7FER201",
        "FACILITY_NAME": "EL TACOLOCO 7FER201",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084367522",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0276130",
        "record_ID": "PR0417280",
        "PROGRAM_IDENTIFIER": "LA ESTRELLITA TAQUERIA #1 4MN7044",
        "FACILITY_NAME": "LA ESTRELLITA TAQUERIA #1 4MN7044",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084367522",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0276832",
        "record_ID": "PR0418364",
        "PROGRAM_IDENTIFIER": "TACOS DEL GUERO 6X02656",
        "FACILITY_NAME": "TACOS DEL GUERO 6X02656",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "NULL",
        "city": "GILROY",
        "ZIP": "95020"
    },
    {
        "facility_id": "FA0276834",
        "record_ID": "PR0418367",
        "PROGRAM_IDENTIFIER": "TLAXIACO'S PIZZA 6S64734",
        "FACILITY_NAME": "TLAXIACO'S PIZZA 6S64734",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0276902",
        "record_ID": "PR0418476",
        "PROGRAM_IDENTIFIER": "EL CAMINANTE AKA SPARTAN TACO TRUCK 5K61992",
        "FACILITY_NAME": "EL CAMINANTE AKA SPARTAN TACO TRUCK 5K61992",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4086132963",
        "city": "SAN JOSE",
        "ZIP": "95123"
    },
   
   
    {
        "facility_id": "FA0277474",
        "record_ID": "PR0419351",
        "PROGRAM_IDENTIFIER": "CMFO - BIRRIA TACOS Y ANTOJITOS ESTILO 4ND1863",
        "FACILITY_NAME": "BIRRIA TACOS Y ANTOJITOS ESTILO JALISCO 4ND1863",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4086188958",
        "city": "SAN JOSE",
        "ZIP": "95122"
    },
    {
        "facility_id": "FA0277483",
        "record_ID": "PR0419360",
        "PROGRAM_IDENTIFIER": "ANTOJITOS PANZAS VERDES 4NL8594",
        "FACILITY_NAME": "ANTOJITOS PANZAS VERDES 4NL8594",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0277554",
        "record_ID": "PR0419498",
        "PROGRAM_IDENTIFIER": "EL TORITO AZTECA 49874M1",
        "FACILITY_NAME": "EL TORITO AZTECA 49874M1",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0277942",
        "record_ID": "PR0420024",
        "PROGRAM_IDENTIFIER": "CHULA PUEBLA 48400T1",
        "FACILITY_NAME": "CHULA PUEBLA 48400T1",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084367522",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
  
    {
        "facility_id": "FA0277988",
        "record_ID": "PR0420096",
        "PROGRAM_IDENTIFIER": "LA PODEROSA AYG TACOS 7W64004",
        "FACILITY_NAME": "LA PODEROSA AYG TACOS 7W64004",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084367522",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0278183",
        "record_ID": "PR0420306",
        "PROGRAM_IDENTIFIER": "EL TACO RANCHERO 7J56022",
        "FACILITY_NAME": "EL TACO RANCHERO 7J56022",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0278936",
        "record_ID": "PR0421047",
        "PROGRAM_IDENTIFIER": "TACOS EL RUFLES 2  89932U1",
        "FACILITY_NAME": "TACOS EL RUFLES 2  89932U1",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4087281358",
        "city": "SAN JOSE",
        "ZIP": "95118"
    },
    
    {
        "facility_id": "FA0279163",
        "record_ID": "PR0421252",
        "PROGRAM_IDENTIFIER": "EL SABROSON 16017C1",
        "FACILITY_NAME": "EL SABROSON 16017C1",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084367522",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0279285",
        "record_ID": "PR0421368",
        "PROGRAM_IDENTIFIER": "TACOS LA CHOCA 12083M1",
        "FACILITY_NAME": "TACOS LA CHOCA 12083M1",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4087172800",
        "city": "SAN JOSE",
        "ZIP": "95122"
    },
    {
        "facility_id": "FA0281272",
        "record_ID": "PR0422364",
        "PROGRAM_IDENTIFIER": "TAQUERIA MONARCAS 4NX1752",
        "FACILITY_NAME": "TAQUERIA MONARCAS 4NX1752",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084367522",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0281318",
        "record_ID": "PR0422407",
        "PROGRAM_IDENTIFIER": "EL BURRITO LOCO 6Y69155",
        "FACILITY_NAME": "EL BURRITO LOCO 6Y69155",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "6502481772",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0281403",
        "record_ID": "PR0422529",
        "PROGRAM_IDENTIFIER": "TACOS EL RUFLES 8R94906",
        "FACILITY_NAME": "TACOS EL RUFLES 8R94906",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4087281358",
        "city": "SAN JOSE",
        "ZIP": "95118"
    },

    {
        "facility_id": "FA0282093",
        "record_ID": "PR0423258",
        "PROGRAM_IDENTIFIER": "DON PAPA SJ 5H14119",
        "FACILITY_NAME": "DON PAPA SJ 5H14119",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084367522",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0282627",
        "record_ID": "PR0423969",
        "PROGRAM_IDENTIFIER": "TACOS SAN AGUSTIN 08834U1",
        "FACILITY_NAME": "TACOS SAN AGUSTIN 08834U1",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0282867",
        "record_ID": "PR0424306",
        "PROGRAM_IDENTIFIER": "QUIROGA TAQUERIA 4NE6614",
        "FACILITY_NAME": "QUIROGA TAQUERIA 4NE6614",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0282929",
        "record_ID": "PR0424407",
        "PROGRAM_IDENTIFIER": "TACOS EL GORDITO 8G90243",
        "FACILITY_NAME": "TACOS EL GORDITO 8G90243",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084367522",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0283236",
        "record_ID": "PR0424863",
        "PROGRAM_IDENTIFIER": "3 HERMANOS MEXICAN GRILL 5N44985",
        "FACILITY_NAME": "3 HERMANOS MEXICAN GRILL 5N44985",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084667406",
        "city": "SAN JOSE",
        "ZIP": "95113"
    },
    {
        "facility_id": "FA0283294",
        "record_ID": "PR0424967",
        "PROGRAM_IDENTIFIER": "LA COSTENITA 6R37259",
        "FACILITY_NAME": "LA COSTENITA 6R37259",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4087268270",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },

    {
        "facility_id": "FA0283413",
        "record_ID": "PR0425118",
        "PROGRAM_IDENTIFIER": "PATRONA TACOS 7DMZ827",
        "FACILITY_NAME": "TACOS PANCHITO 7DMZ827",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084367522",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0283588",
        "record_ID": "PR0425376",
        "PROGRAM_IDENTIFIER": "CMFO-TACOS EL AUSENTE 4VG7981",
        "FACILITY_NAME": "TACOS EL AUSENTE 4VG7981",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082861932",
        "city": "SAN JOSE",
        "ZIP": "95116"
    },
    {
        "facility_id": "FA0283729",
        "record_ID": "PR0425524",
        "PROGRAM_IDENTIFIER": "TACOS LOS 3 REYES #3 4NY6323",
        "FACILITY_NAME": "TACOS LOS 3 REYES #3 4NY6323",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4086493395",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0283761",
        "record_ID": "PR0425551",
        "PROGRAM_IDENTIFIER": "CATO'S TACOS 4PP9005",
        "FACILITY_NAME": "CATO'S TACOS 4PP9005",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0284014",
        "record_ID": "PR0425981",
        "PROGRAM_IDENTIFIER": "CALIFORNIA MEXICAN FOOD 7F84347",
        "FACILITY_NAME": "CALIFORNIA MEXICAN FOOD 7F84347",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0284124",
        "record_ID": "PR0426135",
        "PROGRAM_IDENTIFIER": "ADELITA COCINA CENTRO AMERICANA Y MEXICANA 4TU7259",
        "FACILITY_NAME": "ADELITA COCINA CENTRO AMERICANA Y MEXICANA 4TU7259",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084367572",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0284663",
        "record_ID": "PR0426882",
        "PROGRAM_IDENTIFIER": "TACOS DON JOSE 01432A1",
        "FACILITY_NAME": "TACOS DON JOSE 01432A1",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0284886",
        "record_ID": "PR0427183",
        "PROGRAM_IDENTIFIER": "TACO AXOLOTL 4VK6014",
        "FACILITY_NAME": "TACO AXOLOTL 4ME8550",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "40837911489",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0285113",
        "record_ID": "PR0427491",
        "PROGRAM_IDENTIFIER": "AY CHABELA TAQUERIA 4VW6087",
        "FACILITY_NAME": "AY CHABELA TAQUERIA 4VW6087",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0285208",
        "record_ID": "PR0427606",
        "PROGRAM_IDENTIFIER": "MARISCOS LOS KORAS #2 12448R1",
        "FACILITY_NAME": "MARISCOS LOS KORAS #2 12448R1",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4089262810",
        "city": "SAN JOSE",
        "ZIP": "95116"
    },

    {
        "facility_id": "FA0285406",
        "record_ID": "PR0427881",
        "PROGRAM_IDENTIFIER": "TACOMANIA 4PL5841",
        "FACILITY_NAME": "TACOMANIA 4PL5841",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "NULL",
        "city": "SAN JOSE",
        "ZIP": "95111"
    },
    
    
    
    {
        "facility_id": "FA0286574",
        "record_ID": "PR0429733",
        "PROGRAM_IDENTIFIER": "MEXIQUENA 43755J2",
        "FACILITY_NAME": "MEXIQUENA 43755J2",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0286732",
        "record_ID": "PR0429972",
        "PROGRAM_IDENTIFIER": "FONSECAS MEXICAN FOOD TRUCK 4RE6351",
        "FACILITY_NAME": "FONSECAS MEXICAN FOOD TRUCK 4RE6351",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "NULL",
        "city": "SAN JOSE",
        "ZIP": "95134"
    },
    {
        "facility_id": "FA0286733",
        "record_ID": "PR0429975",
        "PROGRAM_IDENTIFIER": "FERNANDO EL TAQUERO 1TAQERO",
        "FACILITY_NAME": "FERNANDO EL TAQUERO 1TAQERO",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4087706404",
        "city": "SAN JOSE",
        "ZIP": "95125"
    },
    {
        "facility_id": "FA0286862",
        "record_ID": "PR0430239",
        "PROGRAM_IDENTIFIER": "LAS TARASCAS 4LY6549",
        "FACILITY_NAME": "LAS TARASCAS 4LY6549",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0286864",
        "record_ID": "PR0430244",
        "PROGRAM_IDENTIFIER": "TACOS SANTIAGUITO 8X53332",
        "FACILITY_NAME": "TACOS SANTIAGUITO 8X53332",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0286882",
        "record_ID": "PR0430266",
        "PROGRAM_IDENTIFIER": "LOS JAMAYTECOS 65050J2",
        "FACILITY_NAME": "LOS JAMAYTECOS 65050J2",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0286908",
        "record_ID": "PR0430291",
        "PROGRAM_IDENTIFIER": "EL TACO DE ORO 01535H2",
        "FACILITY_NAME": "EL TACO DE ORO 01535H2",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "6507993471",
        "city": "ALVISO",
        "ZIP": "95002"
    },
    
    {
        "facility_id": "FA0286942",
        "record_ID": "PR0430367",
        "PROGRAM_IDENTIFIER": "CON SABOR A MEXICO 4F55323",
        "FACILITY_NAME": "CON SABOR A MEXICO 4F55323",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4083935599",
        "city": "SAN JOSE",
        "ZIP": "95133"
    },
    
        "facility_id": "FA0287122",
        "record_ID": "PR0430676",
        "PROGRAM_IDENTIFIER": "TACOS EL PELON DE OAXACA 4W12920",
        "FACILITY_NAME": "TACOS EL PELON DE OAXACA 4W12920",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4086124994",
        "city": "MORGAN HILL",
        "ZIP": "95037"
    },
    {
        "facility_id": "FA0287466",
        "record_ID": "PR0431191",
        "PROGRAM_IDENTIFIER": "CMFO - LA SONRISA DE CHECKE 4NT6403",
        "FACILITY_NAME": "LA SONRISA DE CHECKE 4NT6403",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082677121",
        "city": "SAN JOSE",
        "ZIP": "95125"
    },
    
    {
        "facility_id": "FA0287617",
        "record_ID": "PR0431414",
        "PROGRAM_IDENTIFIER": "CALIFAS CORP. 4RT5397",
        "FACILITY_NAME": "CALIFAS CORP. 4RT5397",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    
    {
        "facility_id": "FA0289127",
        "record_ID": "PR0433499",
        "PROGRAM_IDENTIFIER": "EL RANCHERO DEL SUR 8K78882",
        "FACILITY_NAME": "EL RANCHERO DEL SUR 8K78882",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0289203",
        "record_ID": "PR0433610",
        "PROGRAM_IDENTIFIER": "LA BURRITA 5N92913",
        "FACILITY_NAME": "LA BURRITA 5N92913",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "6693427337",
        "city": "SAN JOSE",
        "ZIP": "95129"
    },
    
    {
        "facility_id": "FA0289387",
        "record_ID": "PR0433818",
        "PROGRAM_IDENTIFIER": "EL CAMALEON 05737P2",
        "FACILITY_NAME": "EL CAMALEON 05737P2",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0289417",
        "record_ID": "PR0433884",
        "PROGRAM_IDENTIFIER": "TACOS EL POLLO Y EL POLLITO 99654E2",
        "FACILITY_NAME": "TACOS EL POLLO Y EL POLLITO 99654E2",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082185794",
        "city": "SAN JOSE",
        "ZIP": "95111"
    },
    {
        "facility_id": "FA0289442",
        "record_ID": "PR0433910",
        "PROGRAM_IDENTIFIER": "SHAKOS TACOS 86799D1",
        "FACILITY_NAME": "SHAKOS TACOS 86799D1",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4083144823",
        "city": "SAN JOSE",
        "ZIP": "95116"
    },
    {
        "facility_id": "FA0289563",
        "record_ID": "PR0434229",
        "PROGRAM_IDENTIFIER": "LAS MARIAS LONCHERIA 4MK6430",
        "FACILITY_NAME": "LAS MARIAS LONCHERIA 4MK6430",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4087281358",
        "city": "SAN JOSE",
        "ZIP": "95118"
    },
   
    {
        "facility_id": "FA0289786",
        "record_ID": "PR0434662",
        "PROGRAM_IDENTIFIER": "LINDA'S TAQUERIA #1 8E05819",
        "FACILITY_NAME": "LINDA'S TAQUERIA #1 8E05819",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0289808",
        "record_ID": "PR0434688",
        "PROGRAM_IDENTIFIER": "TACOS CHENCHO 4RZ7835",
        "FACILITY_NAME": "TACOS CHENCHO 4RZ7835",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0290310",
        "record_ID": "PR0435347",
        "PROGRAM_IDENTIFIER": "SUPER TACOS EL CONRRO #1 69394R3",
        "FACILITY_NAME": "SUPER TACOS EL CONRRO #2 69394R3",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4083525123",
        "city": "SAN JOSE",
        "ZIP": "95113"
    },
    {
        "facility_id": "FA0290314",
        "record_ID": "PR0435348",
        "PROGRAM_IDENTIFIER": "TACOS Y TLAYUDAS EL ELUTECO 61524X2",
        "FACILITY_NAME": "TACOS Y TLAYUDAS EL ELUTECO 61524X2",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0290491",
        "record_ID": "PR0435614",
        "PROGRAM_IDENTIFIER": "LA JALISCIENSE 22057T2",
        "FACILITY_NAME": "LA JALISCIENSE 22057T2",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0290532",
        "record_ID": "PR0435680",
        "PROGRAM_IDENTIFIER": "ROLLIN OAXACA 76440M2",
        "FACILITY_NAME": "ROLLIN OAXACA 76440M2",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0302568",
        "record_ID": "PR0435736",
        "PROGRAM_IDENTIFIER": "CMFO-TACOS J.L. LP 4SX6938",
        "FACILITY_NAME": "TACOS J.L. LP 4SX6938",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4087281358",
        "city": "SAN JOSE",
        "ZIP": "95127"
    },
    
    {
        "facility_id": "FA0290813",
        "record_ID": "PR0436003",
        "PROGRAM_IDENTIFIER": "EL TORO TACOS 8J99788",
        "FACILITY_NAME": "EL TORO TACOS 8J99788",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "NULL",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0291028",
        "record_ID": "PR0436258",
        "PROGRAM_IDENTIFIER": "LA CHELISA ANTOJITOS 99899E2",
        "FACILITY_NAME": "LA CHELISA ANTOJITOS 99899E2",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4083144823",
        "city": "SAN JOSE",
        "ZIP": "95116"
    },
    
    {
        "facility_id": "FA0291092",
        "record_ID": "PR0436345",
        "PROGRAM_IDENTIFIER": "TACOS EL GUERITO 4RA9196",
        "FACILITY_NAME": "TACOS EL GUERITO 4RA9196",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082595292",
        "city": "SAN JOSE",
        "ZIP": "95127"
    },
    
    {
        "facility_id": "FA0291162",
        "record_ID": "PR0436452",
        "PROGRAM_IDENTIFIER": "TAQUIZAS EL SUSPIRO 77801T2",
        "FACILITY_NAME": "TAQUIZAS EL SUSPIRO 77801T2",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0306002",
        "record_ID": "PR0437199",
        "PROGRAM_IDENTIFIER": "TACOMANIA 4SJ4336",
        "FACILITY_NAME": "TACOMANIA 4SJ4336",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4086085317",
        "city": "SAN JOSE",
        "ZIP": "95111"
    },

    {
        "facility_id": "FA0294169",
        "record_ID": "PR0438493",
        "PROGRAM_IDENTIFIER": "LA COCINA DE CHATITA 4SJ1073",
        "FACILITY_NAME": "LA COCINA DE CHATITA 4SJ1073",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0296186",
        "record_ID": "PR0438930",
        "PROGRAM_IDENTIFIER": "CMFO-ANTOJOS LOS COMPAS 4SZ7946",
        "FACILITY_NAME": "ANTOJOS LOS COMPAS 4SZ7946",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0296394",
        "record_ID": "PR0438956",
        "PROGRAM_IDENTIFIER": "LA OAXAQUENSE 73220V2",
        "FACILITY_NAME": "LA OAXAQUENSE 73220V2",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4087706404",
        "city": "SAN JOSE",
        "ZIP": "95134"
    },
    {
        "facility_id": "FA0296402",
        "record_ID": "PR0438957",
        "PROGRAM_IDENTIFIER": "SPARTAN TACO TRUCK 38699U2",
        "FACILITY_NAME": "SPARTAN TACO TRUCK 38699U2",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4087128161",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0296922",
        "record_ID": "PR0439001",
        "PROGRAM_IDENTIFIER": "COELLO'S FOOD TRUCK 93715E2",
        "FACILITY_NAME": "COELLO'S FOOD TRUCK 93715E2",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "6693199119",
        "city": "SAN JOSE",
        "ZIP": "95122"
    },
    {
        "facility_id": "FA0296954",
        "record_ID": "PR0439003",
        "PROGRAM_IDENTIFIER": "LA CHILANGUITA TACO TRUCK 00178S2",
        "FACILITY_NAME": "LA CHILANGUITA 00178S2",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "2097100037",
        "city": "LOS BANOS",
        "ZIP": "93635"
    },
    
    {
        "facility_id": "FA0297773",
        "record_ID": "PR0439068",
        "PROGRAM_IDENTIFIER": "TACOS EL CHORE 4SM5406",
        "FACILITY_NAME": "TACOS EL CHORE 4SM5406",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4085928785",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0298235",
        "record_ID": "PR0439120",
        "PROGRAM_IDENTIFIER": "MI TAQUERIA LA SUPREMA 4SS5481",
        "FACILITY_NAME": "MI TAQUERIA LA SUPREMA 4SS5481",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0298983",
        "record_ID": "PR0439174",
        "PROGRAM_IDENTIFIER": "CMFO - CON SABOR A MEXICO 4SZ7948",
        "FACILITY_NAME": "CON SABOR A MEXICO 4SZ7948",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4083935599",
        "city": "SAN JOSE",
        "ZIP": "95133"
    },
    {
        "facility_id": "FA0299325",
        "record_ID": "PR0439280",
        "PROGRAM_IDENTIFIER": "CMFO - LA DELICIAS DE TONITA 4SV9903",
        "FACILITY_NAME": "LA DELICIAS DE TONITA 4SV9903",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082505608",
        "city": "SAN JOSE",
        "ZIP": "95127"
    },
    {
        "facility_id": "FA0299326",
        "record_ID": "PR0439284",
        "PROGRAM_IDENTIFIER": "MI RINCONCITO OAXAQUENO D14976E",
        "FACILITY_NAME": "MI RINCONCITO OAXAQUENO 9F35997",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4087080217",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0299340",
        "record_ID": "PR0439297",
        "PROGRAM_IDENTIFIER": "RUTA 100 7Z08824",
        "FACILITY_NAME": "RUTA 100 7Z08824",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    
    {
        "facility_id": "FA0299380",
        "record_ID": "PR0439361",
        "PROGRAM_IDENTIFIER": "JOE'S TACO SHOP 1UA3530",
        "FACILITY_NAME": "JOE'S TACO SHOP 1UA3530",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0299439",
        "record_ID": "PR0439452",
        "PROGRAM_IDENTIFIER": "TACOS SAN JOSE 23760U1",
        "FACILITY_NAME": "TACOS SAN JOSE 23760U1",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0299517",
        "record_ID": "PR0439530",
        "PROGRAM_IDENTIFIER": "TACOS Y JUGOS APOLLO 4SJ1098",
        "FACILITY_NAME": "TACOS Y JUGOS APOLLO 4SJ1098",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082677121",
        "city": "SAN JOSE",
        "ZIP": "95125"
    },
    
    {
        "facility_id": "FA0299695",
        "record_ID": "PR0439799",
        "PROGRAM_IDENTIFIER": "SONORA TAQUERIA 48161P2",
        "FACILITY_NAME": "SONORA TAQUERIA 48161P2",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0299814",
        "record_ID": "PR0439911",
        "PROGRAM_IDENTIFIER": "EL BOMBERO 408 73514C3",
        "FACILITY_NAME": "EL BOMBERO 408 73514C3",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084667406",
        "city": "SAN JOSE",
        "ZIP": "95113"
    },
    {
        "facility_id": "FA0299816",
        "record_ID": "PR0439913",
        "PROGRAM_IDENTIFIER": "CMFO - TACOS DE LA ESQUINA CDMX 4SX8081",
        "FACILITY_NAME": "TACOS DE LA ESQUINA CDMX 4SX8081",
        "PROGRAM_ELEMENT": "FP25",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - LIMITED FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0299839",
        "record_ID": "PR0439933",
        "PROGRAM_IDENTIFIER": "VIRRUETA'S TACOS 8Y27932",
        "FACILITY_NAME": "VIRRUETA'S TACOS 8Y27932",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0300015",
        "record_ID": "PR0440559",
        "PROGRAM_IDENTIFIER": "EL TACO DE ORO 91508S2",
        "FACILITY_NAME": "EL TACO DE ORO 91508S2",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "6507993471",
        "city": "ALVISO",
        "ZIP": "95002"
    },
    {
        "facility_id": "FA0300019",
        "record_ID": "PR0440562",
        "PROGRAM_IDENTIFIER": "NUEVAS GENERACIONES TAQUERIA 9EVASG1",
        "FACILITY_NAME": "NUEVAS GENERACIONES TAQUERIA 9EVASG1",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4088167854",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0300072",
        "record_ID": "PR0440621",
        "PROGRAM_IDENTIFIER": "WONKS STREET TACOS 569994B",
        "FACILITY_NAME": "WONKS STREET TACOS 569994B",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4084013322",
        "city": "SAN JOSE",
        "ZIP": "95125"
    },
    {
        "facility_id": "FA0300155",
        "record_ID": "PR0440722",
        "PROGRAM_IDENTIFIER": "NEZA BIRRIERIA #2 81972G3",
        "FACILITY_NAME": "NEZA BIRRIERIA #2 81972G3",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
    {
        "facility_id": "FA0300168",
        "record_ID": "PR0440734",
        "PROGRAM_IDENTIFIER": "TACOS EL BUEN SABOR #2 8W24687",
        "FACILITY_NAME": "TACOS EL BUEN SABOR #2 8W24687",
        "PROGRAM_ELEMENT": "FP26",
        "PROGRAM_DESCRIPTION": "MOBILE FOOD FACILITY - FULL FOOD PREP",
        "Permit_Status": "FULL, ONGOING PERMIT",
        "PHONE": "4082750700",
        "city": "SAN JOSE",
        "ZIP": "95112"
    },
]